import {
  CURRENT_SCHEMA_VERSION,
  TripSchema,
  validateTrip,
  type BudgetRange,
  type ResearchRequest,
  type ResearchResult,
  type Trip,
} from "@sidequest-atlas/domain";
import type { TripIntelligenceProvider } from "./types.js";

type DestinationInput = ResearchRequest["destinations"][number];

export class LocalTemplateProvider implements TripIntelligenceProvider {
  readonly id = "local-template";

  async createTrip(request: ResearchRequest): Promise<Trip> {
    const slug = request.slug ?? slugify(request.title ?? request.tripId);
    const dates = enumerateDates(request.dates.start, request.dates.end);
    const dayCount = Math.max(1, dates.length);
    const totalBudgetMinor = requestedBudgetMinor(request);
    const dailyBudget = makeBudgetRange(
      Math.floor(totalBudgetMinor / dayCount / 2),
      Math.ceil(totalBudgetMinor / dayCount),
      request.budget.currency,
      request.budget.excludes,
    );
    const totalBudget = makeBudgetRange(
      Math.floor(totalBudgetMinor * 0.8),
      Math.ceil(totalBudgetMinor * 1.2),
      request.budget.currency,
      request.budget.excludes,
    );
    const destinationStays = request.destinations.map((destination) =>
      makeDestinationStay(destination, request, dailyBudget),
    );

    const tripInput = {
      schemaVersion: CURRENT_SCHEMA_VERSION,
      id: request.tripId,
      slug,
      title: request.title ?? titleFromSlug(slug),
      subtitle: "Local planning skeleton",
      travelerId: request.traveler?.id ?? request.travelerId ?? "shen-ruililin",
      startDate: request.dates.start,
      endDate: request.dates.end,
      status: "researching",
      destinations: destinationStays,
      thesis: makeThesis(request),
      questions:
        request.openQuestions.length > 0
          ? request.openQuestions
          : ["What does everyday life here reveal that guidebooks miss?"],
      principles: [
        `Pace: ${request.desiredPace}`,
        "Prefer sourced local texture over generic recommendations.",
        "Keep private logistics out of public content.",
      ],
      anchors: request.existingBookings.map((booking) => ({
        id: `anchor-${booking.id}`,
        title: booking.label,
        kind: "reservation",
        bookingId: booking.id,
        notes: booking.notes,
        claimIds: [],
      })),
      majorChoices: [],
      decisions: [],
      days: dates.map((date, index) =>
        makeDayPlan(date, index, request, destinationForDate(request.destinations, date), dailyBudget),
      ),
      sidequests: [],
      budget: {
        baseCurrency: request.budget.currency,
        exchangeRates: [],
        balancedTotal: totalBudget,
        citySubtotals: destinationStays.map((destination) => ({
          city: destination.city,
          currency: request.budget.currency,
          balanced: totalBudget,
          food: dailyBudget,
          activities: dailyBudget,
          localTransport: dailyBudget,
        })),
        exclusions: request.budget.excludes,
        actualSpend: [],
        confidence: "low",
      },
      sources: [],
      claims: [],
      observations: [],
    };

    return TripSchema.parse(tripInput);
  }

  async research(request: ResearchRequest): Promise<ResearchResult> {
    const trip = await this.createTrip(request);
    const validationReport = validateTrip(trip);
    return {
      schemaVersion: CURRENT_SCHEMA_VERSION,
      requestId: request.tripId,
      status: validationReport.passed ? "validated" : "needs-review",
      generatedAt: new Date().toISOString(),
      trip,
      warnings: ["Generated by LocalTemplateProvider; replace placeholders with researched detail."],
      unresolvedQuestions: request.openQuestions,
      validationReport,
    };
  }
}

function requestedBudgetMinor(request: ResearchRequest): number {
  if (request.budget.amountMinor !== undefined) {
    return Math.max(0, request.budget.amountMinor);
  }
  if (request.budget.amount !== undefined) {
    return Math.max(0, Math.round(request.budget.amount * 100));
  }
  return 0;
}

function makeBudgetRange(
  lowMinor: number,
  highMinor: number,
  currency: string,
  excludes: string[] = [],
): BudgetRange {
  const low = Math.max(0, Math.min(lowMinor, highMinor));
  const high = Math.max(low, highMinor);
  return {
    lowMinor: low,
    highMinor: high,
    currency,
    minorUnit: 2,
    includes: [],
    excludes,
    confidence: "low",
  };
}

function makeDestinationStay(
  destination: DestinationInput,
  request: ResearchRequest,
  dailyBudget: BudgetRange,
): Trip["destinations"][number] {
  const themes = request.interests.length > 0 ? request.interests : ["orientation"];
  return {
    city: destination.city,
    country: destination.country,
    countryCode: destination.countryCode ?? fallbackCountryCode(destination.country),
    arrivalDate: destination.arrival,
    departureDate: destination.departure,
    timeZone: destination.timeZone ?? "UTC",
    themes,
    coreQuestion: `What makes ${destination.city} legible as a local system?`,
    foodStrategy: {
      seasonalFoods: [],
      supermarketExperiments: [],
      studentCafeterias: [],
      workerLunches: [],
      markets: [],
      picnicCombinations: [],
      worthySplurges: [],
      avoidOverpayingFor: [],
      discountTerms: [],
      normalDailyBudget: dailyBudget,
    },
    universities: [],
    companies: [],
    publicInstitutions: [],
    localSystems: [],
  };
}

function makeDayPlan(
  date: string,
  index: number,
  request: ResearchRequest,
  destination: DestinationInput | undefined,
  dailyBudget: BudgetRange,
): Trip["days"][number] {
  const firstDestination = request.destinations[0];
  const city = destination?.city ?? firstDestination?.city ?? "Unknown";
  const country = destination?.country ?? firstDestination?.country ?? "Unknown";
  const themes = request.interests.length > 0 ? request.interests : ["orientation"];
  const theme = themes[index % themes.length] ?? "orientation";
  const dayId = `day-${date}`;

  return {
    id: dayId,
    date,
    city,
    country,
    title: `${city} ${titleFromSlug(theme)}`,
    theme,
    thesisQuestion: request.openQuestions[index % Math.max(1, request.openQuestions.length)] ?? makeThesis(request),
    weatherDependency: "low",
    expectedEnergy: request.desiredPace === "slow" ? "light" : request.desiredPace,
    blocks: [
      {
        id: `${dayId}-orientation`,
        period: "morning",
        title: `Orientation walk in ${city}`,
        description: "Placeholder block for locally researched fieldwork.",
        estimatedCost: dailyBudget,
        whyItMatters: "Creates a first-pass mental map before adding sourced recommendations.",
        observationPrompt: "What local routines are visible before the tourist day begins?",
        bookingRequired: false,
        fixed: false,
        planningStatus: "candidate",
        verificationStatus: "unresearched",
        status: "idea",
        claimIds: [],
      },
    ],
    foodMode: ["market"],
    budget: dailyBudget,
    sidequestPotential: 3,
    fieldworkPrompts: [
      "What infrastructure is easy to miss?",
      "Where do locals trade money for time?",
    ],
    socialPrompts: [],
    fallbackPlans: [],
    reservations: [],
    sourceIds: [],
    claimIds: [],
  };
}

function destinationForDate(
  destinations: DestinationInput[],
  date: string,
): DestinationInput | undefined {
  return destinations.find(
    (destination) => destination.arrival <= date && date <= destination.departure,
  );
}

function enumerateDates(start: string, end: string): string[] {
  const dates: string[] = [];
  let current = start;
  let guard = 0;
  while (current <= end && guard < 370) {
    dates.push(current);
    current = addDays(current);
    guard += 1;
  }
  return dates;
}

function addDays(dateString: string): string {
  const date = new Date(`${dateString}T00:00:00Z`);
  date.setUTCDate(date.getUTCDate() + 1);
  return date.toISOString().slice(0, 10);
}

function makeThesis(request: ResearchRequest): string {
  const places = request.destinations.map((destination) => destination.city).join(", ");
  const interests = request.interests.length > 0 ? request.interests.join(", ") : "everyday systems";
  return `Use ${places || "the trip"} to study ${interests} through grounded sidequests.`;
}

function fallbackCountryCode(country: string): string {
  const letters = country.replace(/[^A-Za-z]/g, "").slice(0, 2).toUpperCase();
  return letters.length === 2 ? letters : "XX";
}

function slugify(value: string): string {
  const slug = value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return slug || "untitled-trip";
}

function titleFromSlug(slug: string): string {
  return slug
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`)
    .join(" ");
}
