import { TripSchema, type Trip } from "@sidequest-atlas/domain";

export const PDF_STUB_MESSAGE =
  "PDF files are not generated by this package. Use the Playwright CLI against the web app or an exported HTML route to produce a PDF artifact.";

export function exportTripToPdfStub(input: Trip): string {
  const trip = TripSchema.parse(input);
  return [
    `# PDF export for ${trip.title}`,
    "",
    PDF_STUB_MESSAGE,
    "",
    "Example:",
    "",
    "```sh",
    `npx playwright pdf http://localhost:3000/trips/${trip.slug}/print ${trip.slug}.pdf`,
    "```",
    "",
  ].join("\n");
}
